# -*- coding: utf-8 -*-
from __future__ import annotations
# (moved up here from just above `import json` — Python requires a
# `from __future__ import` to be the file's first statement, and this file
# has two Colab-generated docstrings before that point, not one.)

"""SRUK Indonesia Project List Scrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mkJwx1dWCIVzXj18REImCWqcEWmHdgXt
"""

# Colab shell-magic line removed here for plain-Python execution:
#   !pip install --quiet requests tqdm
# Run `pip install requests tqdm` yourself before executing this script.

#!/usr/bin/env python3
"""
SRUK Indonesia — Forestry Sector Data Lake Crawler
====================================================

Downloads ALL forestry-sector (FOLU) mitigation projects from the public
SRUK Indonesia API and stores the COMPLETE, unmodified raw JSON for:

  1. The paginated project list
  2. Every individual project's detail record
     (GET /api/statistic/mitigation/{project_id})

No fields are flattened, renamed, dropped, or assumed to have a fixed
schema. Everything is stored exactly as the API returns it.

Output layout
-------------
data/
├── project_list/
│   └── all_projects.json        # full raw list responses, all pages merged
├── raw_details/
│   ├── <registry_no_or_id>.json # one file per project, raw detail response
│   └── ...
├── metadata/
│   ├── crawl_summary.json       # data quality report
│   └── failed_projects.json     # ids that failed after all retries
└── crawler.log                  # full run log

Usage
-----
    pip install requests tqdm
    python sruk_crawler.py

Environment overrides (optional)
---------------------------------
    SRUK_BASE_URL       default: https://api.srukindonesia.id
    SRUK_SCHEMA_ID      default: 3eeeba14-f66f-4aab-9940-f23abf5800e4 (FOLU)
    SRUK_PAGE_SIZE      default: 100
    SRUK_MAX_WORKERS    default: 4   (parallel detail fetches)
    SRUK_TIMEOUT        default: 30  (seconds per request)
    SRUK_MAX_RETRIES    default: 5
"""

import json
import logging
import os
import sys
import time
import random
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import requests

try:
    from tqdm import tqdm
except ImportError:  # graceful fallback if tqdm isn't installed
    def tqdm(iterable=None, total=None, desc=None, **kwargs):
        if iterable is not None:
            return iterable
        return _NoOpBar(total, desc)

    class _NoOpBar:
        def __init__(self, total, desc):
            self.total = total
            self.desc = desc
            self.n = 0

        def update(self, n=1):
            self.n += n

        def close(self):
            pass


# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------

BASE_URL = os.environ.get("SRUK_BASE_URL", "https://api.srukindonesia.id")
LIST_PATH = "/api/mitigation-spe-certificate/mitigation-list-certificates"
DETAIL_PATH_TEMPLATE = "/api/statistic/mitigation/{project_id}"

SCHEMA_ID = os.environ.get("SRUK_SCHEMA_ID", "3eeeba14-f66f-4aab-9940-f23abf5800e4")
STAGE = os.environ.get("SRUK_STAGE", "0")
PAGE_SIZE = int(os.environ.get("SRUK_PAGE_SIZE", "100"))

MAX_WORKERS = int(os.environ.get("SRUK_MAX_WORKERS", "4"))
TIMEOUT = int(os.environ.get("SRUK_TIMEOUT", "30"))
MAX_RETRIES = int(os.environ.get("SRUK_MAX_RETRIES", "5"))
BACKOFF_BASE = 1.5          # seconds; backoff = BACKOFF_BASE * 2**attempt (+ jitter)
BACKOFF_MAX = 60.0

OUTPUT_ROOT = Path("data")
PROJECT_LIST_DIR = OUTPUT_ROOT / "project_list"
RAW_DETAILS_DIR = OUTPUT_ROOT / "raw_details"
METADATA_DIR = OUTPUT_ROOT / "metadata"

USER_AGENT = "sruk-forestry-data-lake-crawler/1.0"


# --------------------------------------------------------------------------
# Logging
# --------------------------------------------------------------------------

def setup_logging() -> logging.Logger:
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    logger = logging.getLogger("sruk_crawler")
    logger.setLevel(logging.DEBUG)
    logger.handlers.clear()

    fmt = logging.Formatter(
        "%(asctime)s | %(levelname)-8s | %(message)s", datefmt="%Y-%m-%d %H:%M:%S"
    )

    file_handler = logging.FileHandler(OUTPUT_ROOT / "crawler.log", encoding="utf-8")
    file_handler.setLevel(logging.DEBUG)
    file_handler.setFormatter(fmt)

    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setLevel(logging.INFO)
    console_handler.setFormatter(fmt)

    logger.addHandler(file_handler)
    logger.addHandler(console_handler)
    return logger


log = setup_logging()


# --------------------------------------------------------------------------
# HTTP helpers — manual retry loop with exponential backoff + jitter
# --------------------------------------------------------------------------

class FetchError(Exception):
    """Raised when a URL could not be fetched after all retries."""


def make_session() -> requests.Session:
    session = requests.Session()
    session.headers.update(
        {
            "User-Agent": USER_AGENT,
            "Accept": "application/json",
        }
    )
    return session


def fetch_json(
    session: requests.Session,
    url: str,
    params: Optional[dict] = None,
    max_retries: int = MAX_RETRIES,
    timeout: int = TIMEOUT,
) -> Any:
    """
    GET a URL and return parsed JSON, retrying with exponential backoff on:
      - connection errors / timeouts
      - HTTP 429 (rate limited)
      - HTTP 5xx (server errors)

    Non-retryable HTTP errors (4xx other than 429) raise immediately.
    Raises FetchError if all retries are exhausted.
    """
    last_exc: Optional[Exception] = None

    for attempt in range(max_retries + 1):
        try:
            resp = session.get(url, params=params, timeout=timeout)

            if resp.status_code == 429 or resp.status_code >= 500:
                raise requests.exceptions.HTTPError(
                    f"Retryable status {resp.status_code}", response=resp
                )

            resp.raise_for_status()  # raises on other 4xx (non-retryable)
            return resp.json()

        except requests.exceptions.HTTPError as e:
            resp = getattr(e, "response", None)
            status = resp.status_code if resp is not None else None
            if status is not None and status < 500 and status != 429:
                # Non-retryable client error (400, 401, 403, 404, etc.)
                log.error(f"Non-retryable HTTP {status} for {url}: {e}")
                raise FetchError(f"HTTP {status} for {url}") from e
            last_exc = e

        except (requests.exceptions.ConnectionError, requests.exceptions.Timeout) as e:
            last_exc = e

        except ValueError as e:  # JSON decode error
            last_exc = e

        if attempt < max_retries:
            sleep_time = min(BACKOFF_MAX, BACKOFF_BASE * (2 ** attempt))
            sleep_time += random.uniform(0, 1.0)  # jitter
            log.warning(
                f"Attempt {attempt + 1}/{max_retries + 1} failed for {url} "
                f"({last_exc}). Retrying in {sleep_time:.1f}s..."
            )
            time.sleep(sleep_time)
        else:
            log.error(f"All {max_retries + 1} attempts failed for {url}: {last_exc}")

    raise FetchError(f"Exhausted retries for {url}") from last_exc


# --------------------------------------------------------------------------
# Step 1: Fetch full project list (with pagination)
# --------------------------------------------------------------------------

def fetch_all_projects(session: requests.Session) -> list[dict]:
    """
    Paginates through the project list endpoint until no more pages remain.
    Returns the list of raw project dicts, completely unmodified.
    Also preserves every raw page response for the data lake.
    """
    all_projects: list[dict] = []
    raw_pages: list[dict] = []
    page = 1

    log.info("Starting project list crawl (forestry / FOLU schema)...")

    while True:
        params = {
            "page": page,
            "pageSize": PAGE_SIZE,
            "stage": STAGE,
            "schema": SCHEMA_ID,
        }
        url = f"{BASE_URL}{LIST_PATH}"
        log.info(f"Fetching project list page {page}...")

        try:
            payload = fetch_json(session, url, params=params)
        except FetchError as e:
            log.error(f"Failed to fetch page {page}, stopping pagination: {e}")
            break

        raw_pages.append({"page": page, "response": payload})

        # Be defensive: don't assume "data" is always present/well-formed.
        page_data = payload.get("data") if isinstance(payload, dict) else None
        if not page_data:
            log.info(f"Page {page} returned no data — pagination complete.")
            break

        all_projects.extend(page_data)
        log.info(
            f"Page {page}: {len(page_data)} projects "
            f"(running total: {len(all_projects)})"
        )

        if len(page_data) < PAGE_SIZE:
            # Short page = last page
            break

        page += 1

    # Persist raw list data exactly as received (all pages, unflattened)
    PROJECT_LIST_DIR.mkdir(parents=True, exist_ok=True)
    with open(PROJECT_LIST_DIR / "all_projects.json", "w", encoding="utf-8") as f:
        json.dump(
            {
                "fetched_at": datetime.now(timezone.utc).isoformat(),
                "total_pages": len(raw_pages),
                "total_projects": len(all_projects),
                "raw_pages": raw_pages,       # every raw page response, untouched
                "data": all_projects,          # merged convenience list
            },
            f,
            ensure_ascii=False,
            indent=2,
        )

    log.info(f"Project list complete: {len(all_projects)} projects across {len(raw_pages)} page(s).")
    return all_projects


# --------------------------------------------------------------------------
# Step 2: Fetch every project's detail record
# --------------------------------------------------------------------------

def safe_filename(project: dict) -> str:
    """
    Prefer a human-readable registry number for the filename (matches the
    example in the spec), falling back to the raw id if registry_no/
    program_code isn't present. Never assumes a fixed schema beyond this.
    """
    name = (
        project.get("registry_no")
        or project.get("program_code")
        or project.get("id")
        or "unknown"
    )
    # sanitize for filesystem safety only — does not alter stored content
    return "".join(c if c.isalnum() or c in "-_." else "_" for c in str(name))


def fetch_project_detail(session: requests.Session, project: dict) -> tuple[str, Optional[dict], Optional[str]]:
    """
    Fetches the full detail record for one project.
    Returns (project_id, raw_json_or_None, error_message_or_None).
    """
    project_id = project.get("id")
    if not project_id:
        return "unknown", None, "Project record missing 'id' field"

    url = f"{BASE_URL}{DETAIL_PATH_TEMPLATE.format(project_id=project_id)}"
    try:
        detail = fetch_json(session, url)
        return project_id, detail, None
    except FetchError as e:
        return project_id, None, str(e)


def download_all_details(session: requests.Session, projects: list[dict]) -> tuple[list[dict], list[dict]]:
    """
    Downloads detail records for every project, in parallel (bounded worker pool),
    with per-request retry/backoff already handled inside fetch_project_detail.
    Returns (successful_records, failed_records).
    """
    RAW_DETAILS_DIR.mkdir(parents=True, exist_ok=True)

    successes: list[dict] = []
    failures: list[dict] = []

    log.info(f"Starting detail download for {len(projects)} projects "
              f"(concurrency={MAX_WORKERS})...")

    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        future_to_project = {
            executor.submit(fetch_project_detail, session, p): p for p in projects
        }

        with tqdm(total=len(projects), desc="Downloading project details", unit="project") as bar:
            for future in as_completed(future_to_project):
                project = future_to_project[future]
                try:
                    project_id, detail_json, error = future.result()
                except Exception as e:  # noqa: BLE001 — catch-all for safety, log & continue
                    project_id = project.get("id", "unknown")
                    detail_json = None
                    error = f"Unexpected exception: {e}"

                if detail_json is not None:
                    filename = safe_filename(project) + ".json"
                    filepath = RAW_DETAILS_DIR / filename
                    with open(filepath, "w", encoding="utf-8") as f:
                        json.dump(detail_json, f, ensure_ascii=False, indent=2)

                    successes.append(
                        {
                            "id": project_id,
                            "registry_no": project.get("registry_no"),
                            "file": str(filepath),
                        }
                    )
                    log.info(f"Saved detail for {project_id} -> {filepath}")
                else:
                    failures.append(
                        {
                            "id": project_id,
                            "registry_no": project.get("registry_no"),
                            "activity": project.get("activity"),
                            "error": error,
                        }
                    )
                    log.error(f"FAILED detail fetch for {project_id}: {error}")

                bar.update(1)

    return successes, failures


# --------------------------------------------------------------------------
# Step 3: Data quality report
# --------------------------------------------------------------------------

def is_empty_value(v: Any) -> bool:
    if v is None:
        return True
    if isinstance(v, (list, dict, str)) and len(v) == 0:
        return True
    return False


def location_is_missing(detail: dict) -> bool:
    """A project counts as 'missing location' if the location object is
    absent or every field inside it is empty/null. Does not assume which
    keys exist inside 'location'."""
    loc = detail.get("location")
    if not isinstance(loc, dict) or not loc:
        return True
    return all(is_empty_value(v) for v in loc.values())


def documents_are_missing(detail: dict) -> bool:
    """A project counts as 'missing documents' if program_documents is
    absent or empty. Does not assume any other document-bearing field."""
    docs = detail.get("program_documents")
    return is_empty_value(docs)


def build_quality_report(
    total_listed: int,
    successes: list[dict],
    failures: list[dict],
) -> dict:
    missing_location = 0
    missing_documents = 0

    for record in successes:
        filepath = Path(record["file"])
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                detail = json.load(f)
        except Exception as e:  # noqa: BLE001
            log.warning(f"Could not re-read {filepath} for quality checks: {e}")
            continue

        if isinstance(detail, dict):
            if location_is_missing(detail):
                missing_location += 1
            if documents_are_missing(detail):
                missing_documents += 1

    report = {
        "total_projects": total_listed,
        "downloaded": len(successes),
        "failed": len(failures),
        "missing_location": missing_location,
        "missing_documents": missing_documents,
        "crawl_timestamp": datetime.now(timezone.utc).isoformat(),
    }
    return report


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main() -> int:
    METADATA_DIR.mkdir(parents=True, exist_ok=True)
    session = make_session()

    log.info("=" * 70)
    log.info("SRUK Indonesia Forestry Data Lake Crawler — starting run")
    log.info(f"Base URL: {BASE_URL}")
    log.info(f"Schema (sector) ID: {SCHEMA_ID}")
    log.info("=" * 70)

    # --- Step 1: project list ---
    projects = fetch_all_projects(session)
    total_listed = len(projects)

    expected = 92
    if total_listed != expected:
        log.warning(
            f"Project count mismatch: expected ~{expected}, got {total_listed}. "
            f"Proceeding anyway — this may reflect real changes on the registry."
        )
    else:
        log.info(f"Project count verified: {total_listed} projects (matches expected ~{expected}).")

    if not projects:
        log.error("No projects retrieved. Aborting before detail download.")
        return 1

    # --- Step 2: project details ---
    successes, failures = download_all_details(session, projects)

    # --- Failed projects file ---
    with open(METADATA_DIR / "failed_projects.json", "w", encoding="utf-8") as f:
        json.dump(
            {
                "failed_count": len(failures),
                "failed_projects": failures,
                "generated_at": datetime.now(timezone.utc).isoformat(),
            },
            f,
            ensure_ascii=False,
            indent=2,
        )

    # --- Step 3: data quality / crawl summary ---
    summary = build_quality_report(total_listed, successes, failures)
    with open(METADATA_DIR / "crawl_summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    log.info("=" * 70)
    log.info("Crawl complete.")
    log.info(json.dumps(summary, indent=2))
    log.info(f"Project list:     {PROJECT_LIST_DIR / 'all_projects.json'}")
    log.info(f"Raw details:      {RAW_DETAILS_DIR}/ ({len(successes)} files)")
    log.info(f"Failed projects:  {METADATA_DIR / 'failed_projects.json'}")
    log.info(f"Crawl summary:    {METADATA_DIR / 'crawl_summary.json'}")
    log.info("=" * 70)

    return 0 if not failures else 2  # non-zero exit if any project failed


if __name__ == "__main__":
    sys.exit(main())

# Commented out IPython magic to ensure Python compatibility.
# %tb

# Colab shell-magic line removed here for plain-Python execution:
#   !zip -r sruk_project_list.zip data
# Zip the output yourself afterward if you want an archive of data/.

